FROM python:3.9.12-bullseye

RUN apt-get update && apt-get -y dist-upgrade

# RUN apt-get install -y lsb-release

# RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb

# RUN dpkg -i mysql-apt-config_0.8.22-1_all.deb

# RUN apt-get update

# RUN apt-get install mysql-apt-config

COPY /flask-app/ /flaskr

WORKDIR /flaskr

EXPOSE 8080

RUN pip install -r requirements.txt

ENTRYPOINT [ "/bin/sh" ]

CMD [ "runner.sh" ]